name: bnkusers up

on:
  workflow_dispatch:
  # schedule:
    # - cron: '0 8 * * *'  # Runs daily at 5am GMT-3

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # or whatever version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        GGL_CREDENTIALS: ${{ secrets.GGL_CREDENTIALS }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
      run: |
        python scripts/main_run.py
